本番環境での各種設定ファイルを編集したので確認をお願いします。
sasa1009/gamecritic pull request #52
Opened 2020-11-01 10:54 UTC by sasa1009

2020-11-02 01:04 UTC, belion-freee requested changes
本番においてはUser名やパスワード、ホスト名などの接続情報は全て秘匿化してください。

2020-11-02 01:04 UTC, belion-freee commented on config/environments/production.rb
> +    user_name: 'gamecritic12345@gmail.com',
本番の設定が丸見えなので、config/storage.ymlのようにcredentialsに登録して参照するようにしてください。

2020-11-02 01:04 UTC, belion-freee commented on config/database.yml
> +  username: root
本番の設定が丸見えなので、config/storage.ymlのようにcredentialsに登録して参照するようにしてください。

2020-11-04 00:04 UTC, sasa1009 commented on config/database.yml
> +  database: <%= Rails.application.credentials.dig(:database, :database) %>
config/credentials.yml.encに追加しました。

2020-11-04 00:05 UTC, sasa1009 commented on config/environments/production.rb
> +    address: Rails.application.credentials.dig(:mail, :address),
config/credentials.yml.encに追加しました。

2020-11-05 02:34 UTC, belion-freee commented on Gemfile
> +    gem 'unicorn'
可能ならunicornよりはpumaの方がいいんですよね。
https://scoutapm.com/blog/which-ruby-app-server-is-right-for-you-ja

あんまpumaの設定に自信ないんですけど、pumaをデーモン設定(バックグラウンドで常に動かしてる状態)してればrailsをバックグラウンド起動できるかも。
https://nishinatoshiharu.com/nginx-puma-rails6-prd/#i-5
https://amiiby.com/0160#toc1

2020-11-05 02:34 UTC, belion-freee commented on config/database.yml
> +  database: <%= Rails.application.credentials.dig(:database, :database) %>
`dig`便利ですよね

2020-11-05 02:34 UTC, belion-freee commented on config/environments/production.rb
> +  config.assets.compile = true
本番環境では動的にコンパイルする必要はないので、falseのままの方がいいのでは？ デプロイ時にコンパイルするので。

2020-11-05 02:34 UTC, belion-freee commented on db/seeds.rb
> +ff7.jacket.attach(io: File.open("#{Rails.root}/db/images/FF7REMAKE.jpg"),
### nits
ファイル名を返すメソッドを用意しても良かったかも。
こんな感じの。
```
def file_path(name)
  File.open("#{Rails.root}/db/images/#{name}.jpg"
end
```

2020-11-05 02:34 UTC, belion-freee reviewed
コンパイルの設定だけ回答お願いします

2020-11-06 11:42 UTC, belion-freee approved these changes
LGTM

2020-11-06 15:07 UTC, merged